(lang dune 3.19)

(name bch_codes_polynomes)

(generate_opam_files true)

(source
 (github nanapiou/polynomes))

(authors "Nanapiou")

(maintainers "Nanapiou")

(license LICENSE)

(package
 (name bch_codes_polynomes)
 (synopsis "Implementation of BCH codes using polynomes themselves")
 (description "...")
 (depends ocaml)
 (tags
  ("error correction codes" "polynomes" "algebra" "ocaml")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
